[book]
title = "notes"
authors = ["beastmatser"]
src = "src"
description = "My personal notes"
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/beastmatser/notes"
